language: java
jdk:
  - oraclejdk8

services: mongodb

install:
  - cd $TRAVIS_BUILD_DIR/api && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: cd $TRAVIS_BUILD_DIR/api && mvn test
